apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mediawiki.componentName" (list . "config") }}
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
data:
  LocalSettings.php: |
{{ tpl .Values.localSettings . | indent 4 }}
