apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.componentName" (list . "database") }}
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "mediawiki.name" . }}
    app.kubernetes.io/component: database
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
