apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediawiki.componentName" (list . "database") }}
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "mediawiki.name" . }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "mediawiki.name" . }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.database.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.auth.username | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.auth.password | quote }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.auth.rootPassword | quote }}
          ports:
            - containerPort: {{ .Values.database.service.port }}
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "mediawiki.componentName" (list . "database-data") }}
