apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediawiki.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mediawiki.name" . }}
    helm.sh/chart: {{ include "mediawiki.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mediawiki.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mediawiki.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mediawiki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "mediawiki.fullname" . }}-db
          env:
            - name: MEDIAWIKI_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki.fullname" . }}-db
                  key: MEDIAWIKI_DB_HOST
            - name: MEDIAWIKI_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki.fullname" . }}-db
                  key: MEDIAWIKI_DB_NAME
            - name: MEDIAWIKI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki.fullname" . }}-db
                  key: MEDIAWIKI_DB_USER
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki.fullname" . }}-db
                  key: MEDIAWIKI_DB_PASSWORD
            - name: MEDIAWIKI_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki.fullname" . }}-db
                  key: MEDIAWIKI_DB_PORT
            - name: MEDIAWIKI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediawiki.fullname" . }}-db
                  key: MEDIAWIKI_SECRET_KEY
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: localsettings
              mountPath: /config/LocalSettings.php
              subPath: LocalSettings.php
{{- if .Values.persistence.enabled }}
            - name: mediawiki-data
              mountPath: {{ .Values.persistence.mountPath }}
{{- end }}
{{- with .Values.deployment.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
      volumes:
        - name: localsettings
          configMap:
            name: {{ include "mediawiki.fullname" . }}-config
{{- if .Values.persistence.enabled }}
        - name: mediawiki-data
          persistentVolumeClaim:
            claimName: {{ include "mediawiki.fullname" . }}-data
{{- end }}
