apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.componentName" (list . "frontend") }}
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "mediawiki.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
