{{- if .Values.frontend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mediawiki.componentName" (list . "frontend") }}
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
    app.kubernetes.io/component: frontend
spec:
  host: {{ .Values.frontend.route.host }}
  to:
    kind: Service
    name: {{ include "mediawiki.componentName" (list . "frontend") }}
  tls:
    termination: edge
{{- end }}
