apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.componentName" (list . "redis") }}
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "mediawiki.name" . }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
